### ISSUE TITLE
Fails to build with GCC 13

### ISSUE THREAD

**Issue by merkys** [samuelflores/molmodel#11]
It has been reported that molmodel 3.1.0 fails to build from source with GCC 13. Full report is [here](https://bugs.debian.org/1037780). Next Debian release (in 2025) will be based on GCC 13.

**Comment by MadCatX** [comment]
Fixed in master

**Comment by merkys** [comment]
I confirm commit 968a0af8bc1a224337a3d1e1bd2fec3aec9e3fa1 fixes the issue.

**Comment by samuelflores** [comment]
great to hear!
