### ISSUE TITLE
Soversion for shared library

### ISSUE THREAD

**Issue by merkys** [samuelflores/molmodel#9]
Until recently (I cannot pinpoint exact commit), molmodel used to build a shared library with a soversion. This was the piece of code which did so, but now seem to be gone:
```CMake
    SET_TARGET_PROPERTIES(${SHARED_TARGET} PROPERTIES
        PROJECT_LABEL "Library - ${SHARED_TARGET}"
        SOVERSION "${MOLMODEL_MAJOR_VERSION}.${MOLMODEL_MINOR_VERSION}")
```

Soversions are important for Debian packaging, as shared libraries without soversions are not exposed publicly. This is not a problem for Debian packaging per se, as private shared libraries or static libraries are also OK. What is more of a problem, is consistency, as switching between public shared, private shared and static is problematic. Thus my question here: is this loss of soversion intended? Maintaining a soversion requires some level of API/ABI stability, thus there is additional burden in it.

**Comment by MadCatX** [comment]
Fixed in https://github.com/samuelflores/molmodel/commit/8bed3539deda854b285eb7ac208613fe7b2401ae

**Comment by merkys** [comment]
Thanks @MadCatX for prompt fix - this should do. Closing.
